// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: Controller/Dto/Proto/product.proto

package Proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string  `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title       string  `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description string  `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Price       float32 `protobuf:"fixed32,4,opt,name=Price,proto3" json:"Price,omitempty"`
	Stock       int32   `protobuf:"varint,5,opt,name=Stock,proto3" json:"Stock,omitempty"`
}

func (x *Product) Reset() {
	*x = Product{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Controller_Dto_Proto_product_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_Controller_Dto_Proto_product_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_Controller_Dto_Proto_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type ProductPage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List      []*Product `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	Page      int32      `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	TotalData int64      `protobuf:"varint,3,opt,name=TotalData,proto3" json:"TotalData,omitempty"`
}

func (x *ProductPage) Reset() {
	*x = ProductPage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Controller_Dto_Proto_product_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductPage) ProtoMessage() {}

func (x *ProductPage) ProtoReflect() protoreflect.Message {
	mi := &file_Controller_Dto_Proto_product_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductPage.ProtoReflect.Descriptor instead.
func (*ProductPage) Descriptor() ([]byte, []int) {
	return file_Controller_Dto_Proto_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductPage) GetList() []*Product {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ProductPage) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ProductPage) GetTotalData() int64 {
	if x != nil {
		return x.TotalData
	}
	return 0
}

var File_Controller_Dto_Proto_product_proto protoreflect.FileDescriptor

var file_Controller_Dto_Proto_product_proto_rawDesc = []byte{
	0x0a, 0x22, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x44, 0x74, 0x6f,
	0x2f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d, 0x0a, 0x07, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x22, 0x63, 0x0a, 0x0b, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x32,
	0x42, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x33,
	0x0a, 0x11, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x47,
	0x72, 0x70, 0x63, 0x12, 0x0e, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x1a, 0x0e, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Controller_Dto_Proto_product_proto_rawDescOnce sync.Once
	file_Controller_Dto_Proto_product_proto_rawDescData = file_Controller_Dto_Proto_product_proto_rawDesc
)

func file_Controller_Dto_Proto_product_proto_rawDescGZIP() []byte {
	file_Controller_Dto_Proto_product_proto_rawDescOnce.Do(func() {
		file_Controller_Dto_Proto_product_proto_rawDescData = protoimpl.X.CompressGZIP(file_Controller_Dto_Proto_product_proto_rawDescData)
	})
	return file_Controller_Dto_Proto_product_proto_rawDescData
}

var file_Controller_Dto_Proto_product_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Controller_Dto_Proto_product_proto_goTypes = []interface{}{
	(*Product)(nil),     // 0: Proto.Product
	(*ProductPage)(nil), // 1: Proto.ProductPage
}
var file_Controller_Dto_Proto_product_proto_depIdxs = []int32{
	0, // 0: Proto.ProductPage.List:type_name -> Proto.Product
	0, // 1: Proto.DataProduct.DetailProductGrpc:input_type -> Proto.Product
	0, // 2: Proto.DataProduct.DetailProductGrpc:output_type -> Proto.Product
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Controller_Dto_Proto_product_proto_init() }
func file_Controller_Dto_Proto_product_proto_init() {
	if File_Controller_Dto_Proto_product_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Controller_Dto_Proto_product_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Product); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Controller_Dto_Proto_product_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductPage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Controller_Dto_Proto_product_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Controller_Dto_Proto_product_proto_goTypes,
		DependencyIndexes: file_Controller_Dto_Proto_product_proto_depIdxs,
		MessageInfos:      file_Controller_Dto_Proto_product_proto_msgTypes,
	}.Build()
	File_Controller_Dto_Proto_product_proto = out.File
	file_Controller_Dto_Proto_product_proto_rawDesc = nil
	file_Controller_Dto_Proto_product_proto_goTypes = nil
	file_Controller_Dto_Proto_product_proto_depIdxs = nil
}
